version: '3'
services:
  # Setup MySQL
  backend_node_graphql_mysql_db:
    image: 'mysql:5.7' 
    ports:
      - 3306:3306 
    restart: always # This will make sure that the container comes up post unexpected shutdowns
    env_file:
      - ./backend-node-graphql-mysql/.env.docker
    volumes:
      - backend-node-graphql-mysql-db-volume:/var/lib/mysql

  # Setup backend-node-graphql-mysql api
  backend-node-graphql-mysql:
    build:
      context: './backend-node-graphql-mysql'
      args:
        ENVIRONMENT_NAME: docker
    ports:
      - 9000:9000
    env_file:
      - ./backend-node-graphql-mysql/.env.docker
    environment:
      ENVIRONMENT_NAME: docker


  # Setup Redis
  redis:
    image: 'redis:6-alpine'
    ports:
      - 6379:6379
    # Default command that redis will execute at start
    command: ['redis-server']

# No web stacks present


# Setup Volumes
volumes:
  backend-node-graphql-mysql-db-volume:

